# This is a basic workflow to help you get started with Actions
name: deploy to lambda

on:
  push:
    paths:
      - 'lambda/**'
    branches: [master]
  pull_request:
    paths:
      - 'lambda/**'
    branches: [ master ]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_zip:
    name: deploy lambda function
    runs-on: ubuntu-latest
    steps:
    - name: deploy
      run: |
        sudo apt-get -y install aws
        mkdir package
        cp lambda/main.py package
        pip install --target ./package -r lambda/requirements.txt
        cd package
        zip -r9 ${OLDPWD}/function.zip
        aws lambda update-function-code --function-name smart-home --zip-file fileb://function.zip
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: ${{ secrets.AWS_REGION }}