# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
      
    - name: Setup Arduino CLI
      uses: arduino/setup-arduino-cli@v1.0.0
      with:
        # Version to use. Example: 0.5.0
        version: '0.x'
    
    - name: Compile 1010 wifi
      run: |
        cd Arduino
        arduino-cli core update-index
        arduino-cli core install arduino:samd
        arduino-cli lib install WiFiNINA
        arduino-cli compile --fqbn arduino:samd:mkrwifi1010 smartswitch
      
